src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use App\Repository\ProjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_categorie;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     */
    #[Vich\UploadableField(mapping: 'categorie_image', fileNameProperty: 'imageName')]
    #[Assert\Image(maxSize:"8M", mimeTypes: ['image/*'], mimeTypesMessage: "Mauvais type de fichier, format pris en charge  PNG|JPEG|JPG|*")]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageName;

    #[ORM\OneToMany(mappedBy: 'secteur', targetEntity: Projet::class, orphanRemoval: true), Ignore]
    private $projet;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     */
    #[Vich\UploadableField(mapping: 'icone', fileNameProperty: 'iconeName')]
    #[Assert\Image(maxSize:"1M", mimeTypes: ['image/svg+xml'], mimeTypesMessage: 'Veuilllez choisir une image SVG')]
    private ?File $iconeFile = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $iconeName;

    /**
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     */
//    #[Gedmo\Locale]
//    private $locale;

    public function __construct()
    {
        $this->projet = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            // $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $iconeFile
     */
    public function setIconeFile(?File $iconeFile = null): void
    {
        $this->iconeFile = $iconeFile;

        if (null !== $iconeFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getIconeFile(): ?File
    {
        return $this->iconeFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjet(): Collection
    {
        return $this->projet;
    }

    public function addProjet(Projet $projet): self
    {
        if (!$this->projet->contains($projet)) {
            $this->projet[] = $projet;
            $projet->setSecteur($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): self
    {
        if ($this->projet->removeElement($projet)) {
            // set the owning side to null (unless already changed)
            if ($projet->getSecteur() === $this) {
                $projet->setSecteur(null);
            }
        }

        return $this;
    }

    public function getIconeName(): ?string
    {
        return $this->iconeName;
    }

    public function setIconeName(?string $iconeName): self
    {
        $this->iconeName = $iconeName;

        return $this;
    }

//    public function setTranslatableLocale($locale)
//    {
//        $this->locale = $locale;
//    }

//    public function getProjetNumber(ProjetRepository $projetRepository):float{
//
//        $total = 0;
//        foreach($this->getProjet() as $id=>$quantite){
//            $quantite = $projetRepository->find($id);
//            $total += $quantite;
//        }
//        return $total;
//    }
}

src/Entity/Maturite.php
<?php

namespace App\Entity;

use App\Repository\MaturiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Ignore;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

#[ORM\Entity(repositoryClass: MaturiteRepository::class)]
class Maturite implements Translatable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[Gedmo\Translatable]
    #[ORM\Column(type: 'string', length: 255)]
    private $nom_maturite;

    #[ORM\OneToMany(mappedBy: 'id_maturite', targetEntity: EltMaturite::class), Ignore]
    private $eltMaturites;

    #[ORM\OneToMany(mappedBy: 'maturite', targetEntity: Projet::class), Ignore]
    private $projet;

    #[Gedmo\Translatable]
    #[ORM\Column(type: 'string', length: 255)]
    private $type;

    #[ORM\ManyToMany(targetEntity: Financement::class, inversedBy: 'maturites'), Ignore]
    private $financements;

    public function __construct()
    {
        $this->eltMaturites = new ArrayCollection();
        $this->projet = new ArrayCollection();
        $this->financements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomMaturite(): ?string
    {
        return $this->nom_maturite;
    }

    public function setNomMaturite(string $nom_maturite): self
    {
        $this->nom_maturite = $nom_maturite;

        return $this;
    }

    /**
     * @return Collection<int, EltMaturite>
     */
    public function getEltMaturites(): Collection
    {
        return $this->eltMaturites;
    }

    public function addEltMaturite(EltMaturite $eltMaturite): self
    {
        if (!$this->eltMaturites->contains($eltMaturite)) {
            $this->eltMaturites[] = $eltMaturite;
            $eltMaturite->setIdMaturite($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjet(): Collection
    {
        return $this->projet;
    }

    public function addProjet(Projet $projet): self
    {
        if (!$this->projet->contains($projet)) {
            $this->projet[] = $projet;
            $projet->setMaturite($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): self
    {
        if ($this->projet->removeElement($projet)) {
            // set the owning side to null (unless already changed)
            if ($projet->getMaturite() === $this) {
                $projet->setMaturite(null);
            }
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, Financement>
     */
    public function getFinancements(): Collection
    {
        return $this->financements;
    }

    public function addFinancement(Financement $financement): self
    {
        if (!$this->financements->contains($financement)) {
            $this->financements[] = $financement;
        }

        return $this;
    }

    public function removeFinancement(Financement $financement): self
    {
        $this->financements->removeElement($financement);

        return $this;
    }
}

templates/index/carte.html.twig
{% extends 'base.html.twig' %}

{% block title 'Carte de projets' %}

{% block body %}


    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">{%trans%}Carte de projet{%endtrans%}</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="{{ path('app_index') }}">{%trans%}Home{%endtrans%}</a></li>
                        <li>{%trans%}Carte de Projet{%endtrans%}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


        <div id="root-carte-project"></div>


{% endblock %}

templates/index/category-project.html.twig
{% extends 'base.html.twig' %}

{% block title 'Projets|category' %}

{% block body %}

    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">{{ categorie.nomCategorie|trans }}</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="{{ path('app_index') }}">{%trans%}Accueil{%endtrans%}</a></li>
                        <li> <a href="{{path('app_project_category')}}"> {%trans%}Secteurs {%endtrans%}</a></li>
                        <li>{{ categorie.nomCategorie|trans }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Start Items Grid Area -->
    <section class="items-grid section custom-padding" style="padding-top: 100px">
        <div class="container">

            {% if projets|length > 0%}
                {% for row in projets|batch(30)%}
                    <div class="single-head">
                        <div class="row">
                            {% for projet in row%}
                                <div class="col-lg-4 col-md-6 col-12">
                                    <!-- Start Single Grid -->
                                    <div class="single-grid wow fadeInUp" data-wow-delay=".2s">
                                        <div class="content">
                                            <div class="top-content">
                                                <a href="javascript:void(0)" class="tag">{{ projet.secteur.nomCategorie|trans }}</a>
                                                <h3 class="title">
                                                    <a href="{{ path('app_project_detail', {'id':projet.id}) }}">{{ projet.institule|trans }}</a>
                                                </h3>
                                                <ul class="info-list">
                                                    {% if projet.arrondissement%}
                                                        <li><a href="javascript:void(0)"><i class="lni lni-map-marker"></i> {{ projet.arrondissement.ville}}</a></li>
                                                        <li><a href="javascript:void(0)"> {%trans%}Region {%endtrans%}: {{projet.arrondissement.departement.region.nom}} CMR</a></li>
                                                    {%else%}
                                                        <li><a href="javascript:void(0)"> Projet régionale de:</a></li>
                                                        <li><a href="javascript:void(0)"> <i class="lni lni-map-marker"></i> {{projet.region.nom}} CMR</a></li>
                                                    {% endif %}
{#                                                    <li><a href="javascript:void(0)"><i class="lni lni-map-marker"></i> {{ projet.arrondissement.ville|trans}}</a></li>#}
{#                                                    <li><a href="javascript:void(0)"> {%trans%}Region{%endtrans%} : {{projet.arrondissement.departement.region.nom|trans}} CMR</a></li>#}
                                                </ul>
                                            </div>
                                            <div class="bottom-content">
                                                <p class="price">{%trans%}Estimation du cout{%endtrans%}: <span>{{ projet.couts }} FCFA</span></p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End Single Grid -->
                                </div>
                            {% endfor%}

                            <div class="row">
                                <div class="col-12">
                                    <div class="pagination right">
                                        <ul class="pagination-list">
                                            {{ knp_pagination_render(projets) }}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor%}
            {% else%}
                <span class="text-center text-danger"> {%trans%}Aucun projet repertorié{%endtrans%}</span>
            {% endif %}
        </div>
    </section>
    <!-- /End Items Grid Area -->

{% endblock %}

templates/index/communal-list-projects.html.twig
{% extends 'base.html.twig' %}

{% block title 'Liste de projets communaux' %}


{% block body %}
    <div id="root-communal-projet"></div>
{% endblock %}

templates/index/detail-project.html.twig
{% extends 'base.html.twig'%}

{% block title 'Details'%}
{% block body%}

    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">{%trans%}Projet Detaillé{%endtrans%}</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="{{ path('app_index') }}">{%trans%}Accueil{%endtrans%}</a></li>
                        <li> {{ projet.institule }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <section class="item-details section">
        <div class="container">
            <div class="top-area">
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-12">
                        <div class="product-images">
                            <main id="gallery">
                                <div class="main-img">
                                    {% for categorie in categories %}
{#                                        <img src="{{ (categorie.imageName ? vich_uploader_asset(categorie, 'imageFile') : asset('image/placeholder.png')) }}" alt="{{ categorie.imageName }}" class="thumbnail" height="200" width="200">#}

{#                                        <img src="{{( vich_uploader_asset(categorie, 'imageFile') | imagine_filter('squared_thumbnail_medium'))}}" id="current" alt="{{projet.secteur.imageName}}" width="auto" height="auto">#}
                                        <img src="{{(categorie.imageName ? vich_uploader_asset(categorie, 'imageFile') : asset('image/placeholder.png')) | imagine_filter('squared_thumbnail_medium')}}" id="current" alt="{{projet.secteur.imageName}}" width="auto" height="auto">
                                    {% endfor%}
                                </div>
{#                                <div class="images">#}
{#                                    <img src="assets/images/item-details/image1.jpg" class="img" alt="#">#}
{#                                    <img src="assets/images/item-details/image2.jpg" class="img" alt="#">#}
{#                                    <img src="assets/images/item-details/image3.jpg" class="img" alt="#">#}
{#                                    <img src="assets/images/item-details/image4.jpg" class="img" alt="#">#}
{#                                    <img src="assets/images/item-details/image5.jpg" class="img" alt="#">#}
{#                                </div>#}
                            </main>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-12">
                        <div class="product-info">
                            <h2 class="title">{{ projet.institule }}</h2>
                            <p class="location">
                                <i class="lni lni-map-marker"></i>
                                {%if projet.arrondissement%}
                                    <a href="javascript:void(0)" class="me-5">{{ projet.arrondissement.ville }}</a>
                                    <a href="javascript:void(0)">{%trans%}Region{%endtrans%} : {{ projet.arrondissement.departement.region.nom }} CMR</a>
                                {%else %}
                                    <a href="javascript:void(0)">{%trans%}Region{%endtrans%} : {{ projet.region.nom }} CMR</a>
                                {%endif%}
                            </p>
                            <span>{%trans%}Estimation du cout{%endtrans%}</span><br>
                            <h3 class="price">

                                {{ projet.couts }} FCFA
                            </h3>
                            <div class="list-info">
                                <h4>{%trans%}Informations{%endtrans%}</h4>
                                <ul>
                                    <li><span> {%trans%}Secteur{%endtrans%}:</span> {{projet.secteur.nomCategorie|trans}}</li>
                                    <li><span>{%trans%}Maturite{%endtrans%}:</span> {{ projet.maturite.nomMaturite }}</li>
                                    {% if projet.statut%}
                                        <li><span>{%trans%}Statut{%endtrans%}:</span> {{ projet.statut.nom }}</li>
                                    {%else%}
                                        <li><span>{%trans%}Statut{%endtrans%}:</span> {%trans%}Indisponible{%endtrans%}</li>
                                    {% endif%}
                                </ul>
                            </div>
                            <div class="contact-info">
                                <ul>
                                    <li>
                                        <a href="tel:+237{{projet.user.phone}}" class="call">
                                            <i class="lni lni-phone-set"></i>
                                            +237 {{projet.user.phone}}
                                            <span>{%trans%}Appeler pour plus d'info{%endtrans%}</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="mailTo:{{projet.user.email}}" class="mail">
                                            <i class="lni lni-envelope"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item-details-blocks">
                <div class="row">
                    <div class="col-lg-8 col-md-7 col-12">

                        <div class="single-block description">
                            <h3>{%trans%}Description{%endtrans%}</h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.objectifs}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Caractéristique de l'activité{%endtrans%}</h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.caracteristique}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Marché cibles{%endtrans%}</h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.marche}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Supply Chain{%endtrans%}</h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.supply}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Facteurs et atouts géographiques de production{%endtrans%}</h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.atouts}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Position sur le complexe des chaines de valeur ajoutée{%endtrans%}</h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.valeurAjouter}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Eligibilité au bénéfice des appuis et
                                arrangement de l’environnement
                                institutionnel{%endtrans%}
                            </h3>
                            <p class="text-start lni-text-align-justify">
                                {{ projet.eligibilite}}
                            </p>
                        </div>

                        <div class="single-block description">
                            <h3>{%trans%}Impact économique{%endtrans%}</h3>
                            <p class="text-start">
                                {{ projet.resultats}}
                            </p>
                        </div>


                        <div class="single-block tags">
                            <h3>{%trans%}Autres infos{%endtrans%}</h3>
                            <ul>
                                {% if projet.eltsMaturite|length > 0%}
                                    <span class="mb-2">{%trans%}Elements de maturite disponibles{%endtrans%}</span> <br>
                                    {% for elt in projet.eltsMaturite%}
                                        <li><a href="javascript:void(0)">{{ elt.nom }}</a></li>
                                    {% endfor%}
                                {% else%}
                                    <li> <span class="">{%trans%}Aucunes informations pour le moment{%endtrans%}</span></li>
                                {% endif%}
                            </ul>
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-5 col-12">
                        <div class="item-details-sidebar">

                            <div class="single-block author">
                                <h3>{%trans%}Publié par{%endtrans%}</h3>
                                <div class="content">
                                    {% for user in users%}
                                        <img src="{{user.photo ? vich_uploader_asset(user, 'image') : asset('image/avatar.png') }}" alt="{{user.firstName}}">
                                        <h4>{{user.firstName}}</h4>
                                        <span>
                                            {% for role in user.roles %}
                                                {% if role == "ROLE_COMMUNALE" %}
                                                   {%trans%} Utilisateur Communale{%endtrans%}
                                                {% elseif role == "ROLE_SUPER_ADMIN" %}
                                                    {%trans%}Super Administrateur{%endtrans%}
                                                {% endif %}
                                            {% endfor %}
                                        </span>
                                    {% endfor%}
                                </div>
                            </div>

                            <div class="single-block ">
                                <h3>{%trans%}Location{%endtrans%}</h3>
                                <div class="mapouter">
                                    <div class="gmap_canvas"><iframe width="100%" height="300" id="gmap_canvas" src="{{ mapUrl }}" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://putlocker-is.org"></a><br>
                                        <style>
                                            .mapouter {
                                                position: relative;
                                                text-align: right;
                                                height: 300px;
                                                width: 100%;
                                            }
                                        </style><a href="https://www.embedgooglemap.net">google map code for website</a>
                                        <style>
                                            .gmap_canvas {
                                                overflow: hidden;
                                                background: none !important;
                                                height: 300px;
                                                width: 100%;
                                            }
                                        </style>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{%endblock%}

templates/index/list-projects.html.twig
{% extends 'base.html.twig' %}

{% block title 'Liste de projets' %}

{% block body %}
    <div id="root-list-projects"></div>
{% endblock %}

templates/index/projectSearch.html.twig
{% extends 'base.html.twig' %}

{% block title 'Projets|category' %}

{% block body %}

    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">{%trans%}Résultat de la recherche{%endtrans%}</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li> {{ projetSearchCount }} {%trans%}Projets trouvés{%endtrans%}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Start Items Grid Area -->
    <section class="items-grid section custom-padding" style="padding-top: 100px">
        <div class="container">

            {% if projetSearch|length > 0%}
                <div class="single-head">
                <div class="row">
                    {% for projet in projetSearch%}
                            <div class="col-lg-4 col-md-6 col-12">
                                <!-- Start Single Grid -->
                                <div class="single-grid wow fadeInUp" data-wow-delay=".2s">
                                    <div class="content">
                                        <div class="top-content">
                                            <a href="javascript:void(0)" class="tag">{{ projet.secteur.nomCategorie|trans }}</a>
                                            <h3 class="title">
                                                <a href="{{ path('app_project_detail', {'id':projet.id}) }}">{{ projet.institule|trans }}</a>
                                            </h3>
                                            <ul class="info-list">
                                                <li><a href="javascript:void(0)"><i class="lni lni-map-marker"></i> {{ projet.arrondissement.ville|trans}}</a></li>
                                                <li><a href="javascript:void(0)"> {%trans%}Region{%endtrans%} : {{projet.arrondissement.departement.region.nom|trans}} CMR</a></li>
                                            </ul>
                                        </div>
                                        <div class="bottom-content">
                                            <p class="price">{%trans%}Estimation du cout{%endtrans%}: <span>{{ projet.couts }} FCFA</span></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Grid -->
                            </div>
                    {% endfor%}
                        </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="pagination left">
                            <ul class="pagination-list">
                                {{ knp_pagination_render(projetSearch) }}
                            </ul>
                        </div>

                    </div>
                </div>

            {% else%}
                <span class="text-center text-danger"> {%trans%}Aucun élément trouvé{%endtrans%}</span>
            {% endif %}
        </div>
    </section>
    <!-- /End Items Grid Area -->

{% endblock %}

templates/index/regional-list-projects.html.twig
{% extends 'base.html.twig' %}

{% block title 'Projets de conseil regional' %}

{% block body %}
    <div id="root-regional-projet"></div>
{% endblock %}